Feature/laser
MissouriMRR/IARC-2019 pull request #12
Opened 2019-01-23 01:42 UTC by jozgd

I made a class to make turning the laser on and off easier.

2019-01-24 00:45 UTC, christopher-o-toole requested changes
There's not much code to review here, but there should definitely be more documentation and application of Python formatting standards.

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/README.md
> + Since we are using RPi.GPIO with the UpBoard you need to use this specific [kernal](https://wiki.up-community.org/RPi.GPIO).
```suggestion
 Since we are using RPi.GPIO with the UpBoard you need to use this specific [kernel](https://wiki.up-community.org/RPi.GPIO).
```

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/laser_class.py
> +class Laser:
Document this using the [numpy documentation style](https://numpydoc.readthedocs.io/en/latest/format.html).

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/laser_class.py
> +        self.laser_pin = laser_pin
```suggestion
        self._laser_pin = laser_pin
```
Private members in Python are generally indicated with an underscore.

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/laser_class.py
> +        GPIO.setup(self.laser_pin, GPIO.OUT) #Sets the given pin as output
```suggestion
        GPIO.setup(self._laser_pin, GPIO.OUT) #Sets the given pin as output
```

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/laser_class.py
> +        GPIO.output(self.laser_pin, GPIO.HIGH)
```suggestion
        GPIO.output(self._laser_pin, GPIO.HIGH)
```

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/laser_class.py
> +        GPIO.output(self.laser_pin, GPIO.LOW)
```suggestion
        GPIO.output(self._laser_pin, GPIO.LOW)
```

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/laser_class.py
> +    def off(self):
Document this function.

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/laser_class.py
> +    def on(self):
Document this function.

2019-01-24 00:45 UTC, christopher-o-toole commented on laser/laser_class.py
> +class Laser:
Also, you may put the constructor documentation under the class declaration.

2019-01-24 01:09 UTC, ClayMav reviewed
The name of the file should definitely be `Laser.py`

2019-01-24 01:09 UTC, ClayMav commented on laser/laser_class.py
> +import RPi.GPIO as GPIO
Couldn't this just become
```suggestion
from RPi import GPIO
```

2019-01-24 01:10 UTC, ClayMav commented on laser/README.md
> + Make a laser object and give it the pin number it is plugged into. Then you can obj.on() and obj.off() to turn it on and off (respectively).
```suggestion
 Make a laser object and give it the pin number it is plugged into. Then you can `obj.on()` and `obj.off()` to turn it on and off (respectively).
```

2019-01-24 02:03 UTC, ClayMav commented on laser/laser.py
> +This file contains the class for the laser.
Contains the control object for the laser mounted on the drones.

2019-01-24 18:01 UTC, ClayMav requested changes
Give this a quick read and you should be good to go.
https://realpython.com/documenting-python-code/

2019-01-24 18:01 UTC, ClayMav commented on laser/laser.py
> +This file contains the class for the laser.
Once this gets cleaned up, we can get it merged

2019-01-24 18:01 UTC, ClayMav commented on laser/laser.py
> +turing the laser on and off easier
Make more specific descriptions

2019-01-24 18:01 UTC, ClayMav commented on laser/laser.py
> +        This funtion turns on the laser bound to the laser object
Dont explain python stuff, explain what this specific function does relative to the Laser object

2019-01-24 18:01 UTC, ClayMav commented on laser/laser.py
> +        This funtion turns off the laser bound to the laser object
Same as above

2019-01-24 18:02 UTC, ClayMav commented
Also, https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html

2019-01-25 22:25 UTC, christopher-o-toole approved these changes
Much better, but I'd change the wording a bit on the class docstring. I'll go ahead and approve and let Clay enforce that as he sees fit.

2019-01-25 22:25 UTC, christopher-o-toole commented on laser/laser.py
> +This class is a controller for the laser on the drone
"This class contains functionality for manipulating the laser mounted on the drone." would be sufficient here.

2019-01-26 02:50 UTC, ClayMav approved these changes
Yeah, its good for me.

2019-01-26 02:50 UTC, ClayMav commented on laser/laser.py
> +This class is a controller for the laser on the drone
Agree with Chris

2019-01-26 19:59 UTC, merged