Serial controller for the servo
MissouriMRR/IARC-2019 pull request #25
Opened 2019-02-14 00:37 UTC by jozgd

2019-02-14 01:43 UTC, ClayMav requested changes
Only minor changes, main thing is that you need to distinguish the coding style of python vs C++

2019-02-14 01:43 UTC, ClayMav commented on laser/serial_controller_class.py
> +class serialController:
```suggestion
class SerialController:
```

2019-02-14 01:43 UTC, ClayMav commented on laser/serial_controller_class.py
> +        self.ser = serial.Serial(port_string,baudrate)
`ser` is a bad name, make it longer so it is a bit more understood what it is

2019-02-14 01:43 UTC, ClayMav commented on laser/serial_controller_class.py
> +    def write_to(self,cmdString):
```suggestion
    def write_to(self, cmd_string):
```

2019-02-14 01:43 UTC, ClayMav commented on laser/serial_controller_class.py
> +        cmdString : str
```suggestion
        cmd_string : str
```

2019-02-14 01:43 UTC, ClayMav commented on laser/serial_controller_class.py
> +        self.ser.write(cmdString.encode())
```suggestion
        self.ser.write(cmd_string.encode())
```

2019-02-14 01:43 UTC, ClayMav commented on laser/sketchServoControl.ino
> +  if(usrInt >180)//if over 180 mod the input by 180 to make it in range
Make 180 a constant at the top of the file

2019-02-14 01:43 UTC, ClayMav commented on laser/sketchServoControl.ino
> +    usrInt = usrInt%180;
use constant for 180

2019-02-14 01:43 UTC, ClayMav commented on laser/sketchServoControl.ino
> +    usrInt = abs(usrInt)%180;
use constant for 180

2019-02-16 04:06 UTC, ClayMav requested changes

2019-02-16 04:06 UTC, ClayMav commented on laser/sketchServoControl.ino
> +  myservo.attach(12);//attach the servo to the pin 12
Make 12 a constant, since the pin may change

2019-02-16 04:06 UTC, ClayMav commented on laser/sketchServoControl.ino
> +  Serial.begin(9600);//start the serial connection at 9600 baudrate
make 9600 a constant, since the baud rate may change

2019-02-16 04:06 UTC, ClayMav commented on laser/sketchServoControl.ino
> +      delay(10);//wait 10 ms
make this 10 a constant, since the time delay should be configurable for more or less smooth rotation

2019-02-16 04:06 UTC, ClayMav commented on laser/sketchServoControl.ino
> +      delay(10);//wait 10 ms
same as above

2019-02-19 18:59 UTC, christopher-o-toole commented
Looks fine to me after the changes requested by Clay were made.

2019-02-19 18:59 UTC, christopher-o-toole approved these changes

2019-02-19 19:02 UTC, ClayMav approved these changes

2019-02-19 19:36 UTC, merged