Changed the long hover to hover at the drone's current altitude
MissouriMRR/IARC-2019 pull request #35
Opened 2019-02-28 01:49 UTC by jozgd

Now the drone will long hover at its current altitude when it runs out of tasks

2019-02-28 04:41 UTC, ClayMav requested changes
I thought we had discussed being able to create hover tasks with no altitude and they would default to the current altitude. Then this line would just not include a height.

2019-02-28 21:14 UTC, Thomas-McKanna commented
I know I told you this would work, but I wasn't thinking of the larger picture. Clay is right in that if the hover task is given no altitude it should default to its current altitude. There could be instances other than when we run out of tasks where we want to make a hover task that remains at current altitude, and we don't want to have to pass in the current altitude as a parameter each time.

I would make altitude an optional argument that defaults to None and then grab the current altitude at the first iteration of perform.

2019-03-05 16:17 UTC, christopher-o-toole submitted a review, later dismissed
Looks fine after the latest commit.

2019-03-07 03:28 UTC, ClayMav requested changes

2019-03-07 03:28 UTC, ClayMav commented on flight/drone/drone_controller.py
> +    def add_hover_task(self, duration=c.DEFAULT_HOVER_DURATION, altitude=None, priority=c.Priorities.LOW):
Just default altitude to be rangefinder distance, since that's the only checking you are doing right now

2019-03-12 18:27 UTC, ClayMav commented
@jozgd Can we get this finished up as well?

2019-03-12 19:07 UTC, ClayMav commented
Fixes #55

2019-03-13 00:00 UTC, Thomas-McKanna approved these changes
I have gone through the code with John and we tested it in the simulator. It seems to be working (we did notice some anomalies in the simulator, such as occasionally drifting slowly downward). I think that this weird behavior was just the simulator acting up, since the changed lines of code in this pull request do not affect changing the altitude, only setting a target altitude.

2019-03-17 07:54 UTC, ClayMav approved these changes

2019-03-19 23:11 UTC, merged