Addidng the drone_console alias as well as the mavlinkbridge service …
MissouriMRR/IARC-2019 pull request #6
Opened 2018-11-11 07:43 UTC by 25cent9

…for future on board computers.

Plz **_LGTM_**

2019-01-05 02:00 UTC, ClayMav requested changes
Can you make a readme for `config/` with explanations for the purpose and use of each thing in here, as well as directions to use each. For the `dronerc` file the directions should be to use `source dronerc` to apply the alias

2019-01-05 02:00 UTC, ClayMav commented on config/alias.txt
> +alias drone_console="sudo service mavlinkbridge stop && sudo mavproxy.py --master=/dev/serial/by-id/usb-3D_Robotics_PX4_FMU_v2.x_0-if00"
Can you instead make this file into a `dronerc` file

2019-01-05 02:01 UTC, ClayMav commented
Sorry tiny commit took 400 years to get reviewed, I forgot it was here.

2019-01-06 06:10 UTC, 25cent9 commented on config/alias.txt
> +alias drone_console="sudo service mavlinkbridge stop && sudo mavproxy.py --master=/dev/serial/by-id/usb-3D_Robotics_PX4_FMU_v2.x_0-if00"
Done

2019-01-06 06:14 UTC, 25cent9 commented
Made changes accordingly.

2019-01-07 04:48 UTC, ClayMav approved these changes
👍

2019-01-07 19:43 UTC, merged